DROP TABLE IF EXISTS `enterprise_comprehensive_info`;
CREATE TABLE `enterprise_comprehensive_info` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ADMIN_DIVISION` varchar(500) DEFAULT NULL COMMENT '行政区域',
  `ORGANIZATION_CODE` varchar(500) DEFAULT NULL COMMENT '组织机构代码',
  `ORGANIZATION_NAME` varchar(500) DEFAULT NULL COMMENT '组织名称',
  `ADDRESS` varchar(500) DEFAULT NULL,
  `LEGAL_PERSON` varchar(500) DEFAULT NULL COMMENT '法人',
  `CONTACT_NUMBER` varchar(50) DEFAULT NULL COMMENT '联系电话',
  `LAND_NATURE` varchar(500) DEFAULT NULL COMMENT '土地性质',
  `LAND_CERT_AREA` varchar(500) DEFAULT NULL COMMENT '土地证面积',
  `ACTUAL_LAND_AREA` varchar(500) DEFAULT NULL COMMENT '实际用地面积',
  `FLOOR_AREA` varchar(500) DEFAULT NULL,
  `IS_RENTED_OUT` varchar(500) DEFAULT NULL COMMENT '是否外租',
  `ENTERPRISE_NAME` varchar(500) DEFAULT NULL COMMENT '企业名',
  `UNIFIED_CREDIT_CODE` varchar(500) DEFAULT NULL COMMENT '统一信用代码',
  `RENTAL_AREA` varchar(500) DEFAULT NULL COMMENT '租赁面积',
  `BUSINESS_STATUS` varchar(500) DEFAULT NULL COMMENT '经营状况',
  `EMPLOYEES_TOTAL_NUMBER` int(11) DEFAULT NULL COMMENT '职工总数',
  `STOPPAGES_NUMBER` int(11) DEFAULT NULL COMMENT '停工人数',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=558 DEFAULT CHARSET=utf8;
